<?php
require_once __DIR__ . '/../backend/db.php';

// Auto-detect tunnel IP from OpenVPN status log
function get_ovpn_tunnel_ips(): array {
    $map = [];
    $status = file_get_contents("/var/log/openvpn/openvpn-status.log");
    if (!$status) return $map;
    $in_routing = false;
    foreach (explode("\n", $status) as $line) {
        if (strpos($line, 'ROUTING TABLE') !== false) { $in_routing = true; continue; }
        if (strpos($line, 'GLOBAL STATS') !== false) break;
        if ($in_routing && strpos($line, ',') !== false) {
            $parts = explode(',', $line);
            if (count($parts) >= 2) $map[trim($parts[1])] = trim($parts[0]);
        }
    }
    return $map;
}



// Sync VPN tunnel status from OpenVPN status log (OpenVPN 2.6 format)
function sync_vpn_status($pdo) {
    $status = @file_get_contents("/var/log/openvpn/openvpn-status.log");
    if (!$status) return;
    $connected = [];
    $tunnel_ips = [];
    foreach (explode("\n", $status) as $line) {
        if (strpos($line, "CLIENT_LIST,") === 0) {
            $parts = explode(",", $line);
            if (count($parts) >= 4 && $parts[1] !== 'Common Name') {
                $connected[] = ['cn' => $parts[1], 'ip' => explode(":", $parts[2])[0]];
            }
        }
        if (strpos($line, "ROUTING_TABLE,") === 0) {
            $parts = explode(",", $line);
            if (count($parts) >= 3 && $parts[1] !== 'Virtual Address') {
                $tunnel_ips[$parts[2]] = $parts[1];
            }
        }
    }
    $tunnels = $pdo->query("SELECT id, status FROM vpn_tunnels ORDER BY id")->fetchAll(PDO::FETCH_ASSOC);
    $used = 0;
    foreach ($tunnels as $t) {
        if ($used < count($connected)) {
            $c = $connected[$used];
            $tip = $tunnel_ips[$c['cn']] ?? null;
            $pdo->prepare("UPDATE vpn_tunnels SET status='connected', client_ip=?, tunnel_ip=? WHERE id=?")
                 ->execute([$c['ip'], $tip, $t['id']]);
            // Apply routes from DB to server routing table
            if ($tip) {
                $row = $pdo->query("SELECT routes_json FROM vpn_tunnels WHERE id=" . (int)$t['id'])->fetch();
                $routes = $row['routes_json'] ? json_decode($row['routes_json'], true) : [];
                foreach ((array)$routes as $rt) {
                    $rt = trim($rt);
                    if ($rt) exec("ip route replace $rt via $tip dev tun0 2>/dev/null");
                }
            }
            $used++;
        } else {
            $pdo->prepare("UPDATE vpn_tunnels SET status='disconnected', client_ip=NULL, tunnel_ip=NULL WHERE id=? AND status != 'disconnected'")
                 ->execute([$t['id']]);
        }
    }
}

if (!isset($_SESSION["smartolt_role"]) || $_SESSION["smartolt_role"] !== "superadmin") {
    $_SESSION["error"] = "Akses ditolak!";
    header("Location: ../dashboard.php");
    exit;
}

sync_vpn_status($pdo);

// --- POST handlers ---
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $tok = $_POST['csrf_token'] ?? '';
    if (!$tok || $tok !== ($_SESSION['csrf_token'] ?? '')) {
        header('Location: vpn-tunnels.php'); exit;
    }
    $act = $_POST['action'] ?? '';

    if ($act === 'add') {
        $u = trim($_POST['username'] ?? '');
        $p = trim($_POST['password'] ?? '');
                $routes_raw = $_POST['routes'] ?? [];
        $routes = [];
        foreach ((array)$routes_raw as $r) {
            $r = trim($r);
            if ($r !== '') $routes[] = $r;
        }
        if ($u && $p) {
            $stmt = $pdo->prepare("INSERT INTO vpn_tunnels (username, password, routes_json) VALUES (?,?,?)");
            $stmt->execute([$u, $p, $routes ? json_encode($routes) : null]);
            sync_chap_secrets($pdo);
        }
    } elseif ($act === 'update' && ($id = (int)($_POST['id'] ?? 0))) {
        $p = trim($_POST['password'] ?? '');
                $routes_raw = $_POST['routes'] ?? [];
        $routes = [];
        foreach ((array)$routes_raw as $r) {
            $r = trim($r);
            if ($r !== '') $routes[] = $r;
        }
        if ($p) {
            $stmt = $pdo->prepare("UPDATE vpn_tunnels SET password=?, routes_json=? WHERE id=?");
            $stmt->execute([$p, $routes ? json_encode($routes) : null, $id]);
            sync_chap_secrets($pdo);
        }
    } elseif ($act === 'delete' && ($id = (int)($_POST['id'] ?? 0))) {
        $pdo->prepare("DELETE FROM vpn_tunnels WHERE id=?")->execute([$id]);
        sync_chap_secrets($pdo);
    }
    header('Location: vpn-tunnels.php'); exit;
}

// Sync /etc/ppp/chap-secrets from DB
function sync_chap_secrets($pdo) {
    $rows = $pdo->query("SELECT username, password FROM vpn_tunnels")->fetchAll(PDO::FETCH_ASSOC);
    $lines = ["# Auto-generated by SmartOLT — do not edit manually", "# client    server    secret    IP addresses"];
    foreach ($rows as $r) {
        $lines[] = $r['username'] . "    l2tp-server    " . $r['password'] . "    *";
    }
    file_put_contents('/etc/ppp/chap-secrets', implode("\n", $lines) . "\n");
}

// Check live L2TP sessions
function get_l2tp_sessions() {
    $sessions = [];
    $output = [];
    exec('cat /var/run/xl2tpd/l2tp-control 2>/dev/null && echo "show sessions" | socat - UNIX-CONNECT:/var/run/xl2tpd/l2tp-control 2>/dev/null', $output);
    // Fallback: parse /proc or status file
    $output2 = [];
    exec('ip l2tp show session 2>/dev/null', $output2);
    foreach ($output2 as $line) {
        if (preg_match('/Session\s+(\d+)\s+in\s+tunnel\s+(\d+)/i', $line, $m)) {
            $sessions[$m[1]] = ['tunnel_id' => $m[2]];
        }
    }
    // Get tunnel info for peer IPs
    $output3 = [];
    exec('ip l2tp show tunnel 2>/dev/null', $output3);
    $tunnels = [];
    foreach ($output3 as $line) {
        if (preg_match('/Tunnel\s+(\d+).*peer_address=(\S+)/i', $line, $m)) {
            $tunnels[$m[1]] = $m[2];
        }
    }
    // Get PPP interfaces for IP assignment
    $output4 = [];
    exec('ip -o link show type ppp 2>/dev/null', $output4);
    $ppp_ips = [];
    foreach ($output4 as $line) {
        if (preg_match('/(ppp\d+).*state\s+(UP|DOWN)/i', $line, $m)) {
            $ppp_ips[$m[1]] = ['state' => $m[2]];
        }
    }
    return ['sessions' => $sessions, 'tunnels' => $tunnels, 'ppp' => $ppp_ips];
}

$tunnels = $pdo->query("SELECT * FROM vpn_tunnels ORDER BY username")->fetchAll(PDO::FETCH_ASSOC);
$live = get_l2tp_sessions();

$edit_tunnel = null;
if (isset($_GET['edit'])) {
    $eid = (int)$_GET['edit'];
    foreach ($tunnels as $t) { if ((int)$t['id'] === $eid) { $edit_tunnel = $t; break; } }
}

// Stats
$total = count($tunnels);
$connected = 0;
foreach ($tunnels as $t) { if ($t['status'] === 'connected') $connected++; }
$disconnected = $total - $connected;

include __DIR__ . '/header.php';
?>

<div class="stats-grid">
    <div class="stat-card"><div class="stat-icon bg-blue"><i data-lucide="network"></i></div><div class="stat-info"><h3>Total Tunnels</h3><p><?= $total ?></p></div></div>
    <div class="stat-card"><div class="stat-icon bg-green"><i data-lucide="wifi"></i></div><div class="stat-info"><h3>Connected</h3><p><?= $connected ?></p></div></div>
    <div class="stat-card"><div class="stat-icon bg-red"><i data-lucide="wifi-off"></i></div><div class="stat-info"><h3>Disconnected</h3><p><?= $disconnected ?></p></div></div>
    <div class="stat-card"><div class="stat-icon bg-purple"><i data-lucide="route"></i></div><div class="stat-info"><h3>Subnet</h3><p>10.198.198.0/24</p></div></div>
</div>

<div class="content-card">
    <div class="card-header">
        <h2><i data-lucide="shield" style="width:18px;height:18px;"></i> VPN Tunnels</h2>
        <div style="display:flex;gap:8px;align-items:center;">
            <button class="btn btn-primary btn-sm" onclick="document.getElementById('add-modal').classList.add('open')">
                <i data-lucide="plus" style="width:14px;height:14px;"></i> Add VPN
            </button>
        </div>
    </div>

<?php if (empty($tunnels)): ?>
    <div style="text-align:center;padding:60px 20px;color:var(--text-muted);">
        <i data-lucide="shield-off" style="width:48px;height:48px;opacity:0.3;"></i>
        <p style="margin-top:12px;">Belum ada VPN tunnel</p>
    </div>
<?php else: ?>
    <div class="table-responsive">
        <table class="data-table">
            <thead>
                <tr>
                    <th>Status</th>
                    <th>Username</th>
                    <th>Client IP</th>
                    <th>Tunnel IP</th>
                    <th>Routes</th>
                    <th>Subnet</th>
                    <th>Aksi</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($tunnels as $t):
                $routes = $t['routes_json'] ? json_decode($t['routes_json'], true) : [];
                $routes_count = is_array($routes) ? count($routes) : 0;
                $is_connected = $t['status'] === 'connected';
            ?>
                <tr>
                    <td>
                        <span class="badge <?= $is_connected ? 'badge-green' : 'badge-red' ?>" style="font-size:11px;">
                            <i data-lucide="<?= $is_connected ? 'wifi' : 'wifi-off' ?>" style="width:12px;height:12px;"></i>
                            <?= $is_connected ? 'Connected' : 'Disconnected' ?>
                        </span>
                    </td>
                    <td class="mono"><?= htmlspecialchars($t['username']) ?></td>
                    <td><?= $t['client_ip'] ? htmlspecialchars($t['client_ip']) : '<span style="color:var(--text-muted)">—</span>' ?></td>
                    <td class="mono"><?= htmlspecialchars($t['tunnel_ip'] ?? '-') ?></td>
                    <td>
                        <?php if ($routes_count > 0): ?>
                            <span class="badge badge-blue"><?= $routes_count ?> route<?= $routes_count > 1 ? 's' : '' ?></span>
                        <?php else: ?>
                            <span style="color:var(--text-muted)">—</span>
                        <?php endif; ?>
                    </td>
                    <td class="mono" style="font-size:12px;"><?= htmlspecialchars($t['subnet'] ?? '10.198.198.0/24') ?></td>
                    <td>
                        <div style="display:flex;gap:4px;">
                            <button class="btn btn-xs btn-outline" onclick="showMikrotik(<?= $t['id'] ?>)" title="Setup MikroTik">
                                <i data-lucide="terminal" style="width:13px;height:13px;"></i>
                            </button>
                            <a href="vpn-tunnels.php?edit=<?= $t['id'] ?>" class="btn btn-xs btn-outline" title="Edit">
                                <i data-lucide="pencil" style="width:13px;height:13px;"></i>
                            </a>
                            <form method="post" style="display:inline;" onsubmit="return confirm('Hapus tunnel <?= htmlspecialchars($t['username']) ?>?')">
                                <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token']) ?>">
                                <input type="hidden" name="action" value="delete">
                                <input type="hidden" name="id" value="<?= $t['id'] ?>">
                                <button type="submit" class="btn btn-xs btn-outline" style="color:var(--color-red);" title="Hapus">
                                    <i data-lucide="trash-2" style="width:13px;height:13px;"></i>
                                </button>
                            </form>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>
</div>

<!-- ADD MODAL -->
<div class="modal" id="add-modal">
    <div class="modal-content" style="max-width:520px;">
        <div class="modal-header"><h3>Add VPN Tunnel</h3></div>
        <form method="post">
            <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token']) ?>">
            <input type="hidden" name="action" value="add">
            <div class="modal-body">
                <div class="form-grid">
                    <div class="form-group"><label>Username</label><input type="text" name="username" class="form-control" required placeholder="mikrotik-01"></div>
                    <div class="form-group"><label>Password</label><input type="text" name="password" class="form-control" required></div>
                </div>
                <!-- Tunnel IP auto-assigned by OpenVPN server -->
                <div class="form-group">
                    <label>Tunnel Routes <small style="color:var(--text-muted)">(subnet per baris, contoh: 192.168.1.0/24)</small></label>
                    <div id="add-routes-container">
                        <input type="text" name="routes[]" class="form-control" placeholder="192.168.1.0/24" style="margin-bottom:4px;">
                    </div>
                    <button type="button" class="btn btn-xs btn-outline" onclick="addRouteRow('add-routes-container')">+ Tambah Route</button>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" onclick="document.getElementById('add-modal').classList.remove('open')">Batal</button>
                <button type="submit" class="btn btn-primary">Simpan</button>
            </div>
        </form>
    </div>
</div>

<!-- EDIT MODAL -->
<?php if ($edit_tunnel):
    $edit_routes = $edit_tunnel['routes_json'] ? json_decode($edit_tunnel['routes_json'], true) : [];
    if (!is_array($edit_routes)) $edit_routes = [];
    if (empty($edit_routes)) $edit_routes = [''];
?>
<div class="modal open">
    <div class="modal-content" style="max-width:520px;">
        <div class="modal-header"><h3>Edit VPN Tunnel — <?= htmlspecialchars($edit_tunnel['username']) ?></h3></div>
        <form method="post">
            <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token']) ?>">
            <input type="hidden" name="action" value="update">
            <input type="hidden" name="id" value="<?= $edit_tunnel['id'] ?>">
            <div class="modal-body">
                <div class="form-group"><label>Username</label><input type="text" class="form-control" value="<?= htmlspecialchars($edit_tunnel['username']) ?>" disabled></div>
                <div class="form-grid">
                    <div class="form-group"><label>Password</label><input type="text" name="password" class="form-control" required value="<?= htmlspecialchars($edit_tunnel['password']) ?>"></div>
                    <!-- Tunnel IP auto-assigned by OpenVPN server -->
                </div>
                <div class="form-group">
                    <label>Tunnel Routes</label>
                    <div id="edit-routes-container">
                        <?php foreach ($edit_routes as $r): ?>
                            <input type="text" name="routes[]" class="form-control" value="<?= htmlspecialchars($r) ?>" placeholder="192.168.1.0/24" style="margin-bottom:4px;">
                        <?php endforeach; ?>
                    </div>
                    <button type="button" class="btn btn-xs btn-outline" onclick="addRouteRow('edit-routes-container')">+ Tambah Route</button>
                </div>
            </div>
            <div class="modal-footer">
                <a href="vpn-tunnels.php" class="btn btn-secondary">Batal</a>
                <button type="submit" class="btn btn-primary">Simpan</button>
            </div>
        </form>
    </div>
</div>
<?php endif; ?>

<!-- SETUP MIKROTIK MODAL -->
<div class="modal" id="mt-modal">
    <div class="modal-content" style="max-width:620px;">
        <div class="modal-header"><h3>Setup MikroTik — <span id="mt-username"></span></h3></div>
        <div class="modal-body">
            <div id="mt-enable-area" style="display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:180px;gap:12px;">
                <p style="font-size:14px;color:var(--text-muted);">Aktifkan download cert untuk setup VPN</p>
                <button type="button" id="cert-enable-btn" class="btn btn-primary" onclick="toggleCertAccess()" style="padding:10px 28px;font-size:14px;">Enable Cert Download (5m)</button>
            </div>
            <div id="mt-script-area" style="display:none;">
                <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;">
                    <p style="font-size:13px;color:var(--text-muted);margin:0;">Copy-paste script ini ke terminal MikroTik:</p>
                    <span id="cert-countdown" style="font-size:13px;color:#ef4444;font-weight:600;"></span>
                </div>
                <textarea id="mt-script" class="form-control" rows="14" style="font-family:monospace;font-size:12px;resize:vertical;" readonly></textarea>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" onclick="document.getElementById('mt-modal').classList.remove('open')">Tutup</button>
            <button type="button" id="mt-copy-btn" class="btn btn-primary" onclick="copyMtScript()" style="display:none;">Copy Script</button>
        </div>
    </div>
</div>

<script>
// Tunnel data for MikroTik script generator
const tunnels = <?= json_encode($tunnels, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP) ?>;
const apiToken = "<?= trim(file_get_contents('/opt/genieacs/certs/.api-token')) ?>";
const serverIP = "smartolt.netbackup.my.id";

function addRouteRow(containerId) {
    const c = document.getElementById(containerId);
    const input = document.createElement('input');
    input.type = 'text'; input.name = 'routes[]'; input.className = 'form-control';
    input.placeholder = '192.168.1.0/24'; input.style.marginBottom = '4px';
    c.appendChild(input);
}

function showMikrotik(id) {
    const t = tunnels.find(x => x.id == id);
    if (!t) return;
    document.getElementById('mt-username').textContent = t.username;
    const url = location.origin + '/vpn/' + id + '/' + apiToken + '.rsc';
    const rscName = 'setup-VPN-Erlangga-SmartOLT-' + t.username + '.rsc';
    const dq = String.fromCharCode(34);
    const bs = String.fromCharCode(92);
    let src = '/tool fetch url=' + bs + dq + url + bs + dq + ' dst-path=' + rscName;
    src += bs + 'n:delay 3s' + bs + 'n/import ' + rscName;
    let script = '/system script add name=vpn-setup source=' + dq + src + dq + '\n';
    script += '/system script run vpn-setup';
    document.getElementById('mt-script').value = script;
    document.getElementById('mt-modal').classList.add('open');
}

function copyMtScript() {
    const ta = document.getElementById('mt-script');
    ta.select(); document.execCommand('copy');
}

function toggleCertAccess() {
    fetch('/api-vpn-cert-toggle.php', {method:'POST', headers:{'Content-Type':'application/x-www-form-urlencoded'}, body:'action=enable'})
    .then(r => r.json()).then(d => {
        if (d.ok) {
            document.getElementById('mt-enable-area').style.display = 'none';
            document.getElementById('mt-script-area').style.display = 'block';
            document.getElementById('mt-copy-btn').style.display = '';
            startCertCountdown(d.expires);
        }
    });
}

let certTimer = null;
function startCertCountdown(expires) {
    if (certTimer) clearInterval(certTimer);
    certTimer = setInterval(() => {
        const left = Math.max(0, Math.floor(expires - Date.now()/1000));
        const m = Math.floor(left/60);
        const s = left % 60;
        document.getElementById('cert-countdown').textContent = m + ':' + String(s).padStart(2,'0');
        if (left <= 0) {
            clearInterval(certTimer);
            document.getElementById('mt-enable-area').style.display = '';
            document.getElementById('mt-script-area').style.display = 'none';
            document.getElementById('mt-copy-btn').style.display = 'none';
            document.getElementById('cert-countdown').textContent = '';
            fetch('/api-vpn-cert-toggle.php', {method:'POST', headers:{'Content-Type':'application/x-www-form-urlencoded'}, body:'action=disable'});
        }
    }, 1000);
}

// Check if already active on page load
fetch('/api-vpn-cert-toggle.php').then(r=>r.json()).then(d => {
    if (d.active) {
        document.getElementById('mt-enable-area').style.display = 'none';
        document.getElementById('mt-script-area').style.display = 'block';
        document.getElementById('mt-copy-btn').style.display = '';
        startCertCountdown(d.expires);
    }
});
</script>

<?php include __DIR__ . '/footer.php'; ?>
